# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	
	#Jenkins Slave server VM configuration
	config.vm.define "slave" do |slave|
		slave.vm.box = "ubuntu/trusty64"
		slave.vm.hostname = 'slave'
		slave.vm.network "public_network"
		slave.vm.synced_folder "./partager", "/home/ubuntu/partager", :create => true
		#app.vm.provision :shell, :path => "elkpartager/setup.bash"
		
		slave.vm.provider :virtualbox do |vb|
		  vb.customize ["modifyvm", :id, "--memory", 768]
		  vb.customize ["modifyvm", :id, "--name", "slave"]
		end
	end
	
end